SELECT COUNTRY_ID,
RANK() OVER (PARTITION BY COUNTRY_ID ORDER BY CITY_ID ASC) AS R
FROM CITY;

SELECT RN2,RN,CID FROM
(SELECT RANK()OVER (ORDER BY COUNTRY_ID ASC )AS RN
RANK() OVER (PARTITION BY COUNTRY_ID ORDER BY CITY_ID ASC) AS RN2,
COUNTRY_ID AS CID,
CITY_ID
FROM CITY
ORDER BY COUNTRY_ID ASC;


SELECT T1.SALARY,T1.ENAME 
FROM EMPLOY3 T1 
WHERE 1-1=(SELECT DISTINCT(COUNT(T2.SALARY))
FROM EMPLOY3 T2
 WHERE T1.SALARY<T2.SALARY);
